### ISSUE TITLE
Trying to return lyrics for a song with full lyrics unavailable raises unhandled IndexError (LYRICSnMUSIC api)

### ISSUE THREAD

**Issue by ysim** [ysim/songtext#30]
```
$ songtext --api lyricsnmusic -t 'the point of no return' -l

40 track(s) matched your search query.


Displaying the top 10 matches:

  0. : The Point of No Return
     ("Passarino - go away!"...)
  1. Geto Boys: Point of No Return
     ("Intro:"...)
  2. Electric Light Orchestra: Point of No Return [#] (full lyrics unavailable)
  3. Duran Duran: Point of No Return
     ("The random aspects of our lives"...)
  4. Andrew Lloyd Webber: Point of No Return
     ("You have come here"...)
  5. Buzzcocks: Point of No Return
     ("If I could discover"...)
  6. Andrew Lloyd Webber and London Symphony Orchestra: The point of no return
     ("You have come here"...)
  7. Status Quo: Point of No Return (full lyrics unavailable)
  8. Paul Weller: Whole Point of No Return
     ("The Lords and Ladies pass a ruling."...)
  9. Napalm Death: Point of No Return
     ("Systematic rape of nature"...)

ysim:~$ songtext --api lyricsnmusic -t 'the point of no return' -i 2

40 track(s) matched your search query.


Traceback (most recent call last):
  File "/usr/local/bin/songtext", line 9, in <module>
    load_entry_point('songtext==0.1.5', 'console_scripts', 'songtext')()
  File "/usr/local/lib/python2.7/site-packages/libsongtext/songtext.py", line 48, in main
    cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/libsongtext/songtext.py", line 43, in cli
    return getattr(api_module, 'get_result')(params)
  File "/usr/local/lib/python2.7/site-packages/libsongtext/lyricsnmusic.py", line 107, in get_result
    output_song(tracklist.get_lyrics(), args['no_pager'])
  File "/usr/local/lib/python2.7/site-packages/libsongtext/lyricsnmusic.py", line 89, in get_lyrics
    element = page_html.cssselect(self.CSS_SELECTOR)[0]
IndexError: list index out of range
```

**Comment by ysim** [comment]
This API is no longer in operation.
